### ISSUE TITLE
Ignore Form Key Block on Catalogue View Page

### ISSUE THREAD

**Issue by JamesJohnsonOnstate** [colinmollenhour/Cm_Diehard#25]
The Form Key block is being cached on the Catalogue View page, so when a user comes to the page their form key is incorrect.

I've updated formkey.phtml to
```
<?php Mage::registry('diehard')->addIgnoredBlock($this); ?>
<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
```

I've also added the following to my themes local.xml
```
<catalog_category_layered>
	<reference name="formkey">
		<action method="addDefaultIgnored" />
		<action method="setBlockIsDynamic"></action>
	</reference>
</catalog_category_layered>
```

But the block is still being cached. Please, could you point me in the right direction?

Thanks

**Comment by colinmollenhour** [comment]
I think it should work with just the layout update if you add also:

```
<action method="setSuppressOutput"><param>1</param></action>
```

Then be sure to add the formkey block to the dynamic handle (e.g. DIEHARD_DYNAMIC_default).

**Comment by JamesJohnsonOnstate** [comment]
Hi Colin,

I've updated the diehardconfig.xml so that the DIEHARD_DYNAMIC_default now contains
```
<DIEHARD_DYNAMIC_default>
    <reference name="header">
        <block type="page/template_links" name="top.links" as="topLinks"/>
        <block type="checkout/cart_sidebar" name="cart_sidebar_top" as="topCart" template="checkout/cart/cartheader.phtml"/>
        <block type="checkout/cart_sidebar" name="cart_sidebar_top_mobile" as="topCartMobile" template="checkout/cart/cartheader.phtml"/>
        <block type="page/html_welcome" name="welcome" as="welcome"/>
        <block type="core/template" name="mobile.cart.switch" as="mobileCart" template="page/html/mobile_cart.phtml" />
    </reference>
    <reference name="root">
        <block name="formkey" type="core/template" template="core/formkey.phtml" />
    </reference>
</DIEHARD_DYNAMIC_default>
```

I've also updated local.xml with
```
<reference name="formkey">
    <action method="addDefaultIgnored" />
    <action method="setBlockIsDynamic"></action>
    <action method="setSuppressOutput"><param>1</param></action>
</reference>
```

Something is happening because the Form Key block is now replaced with `<div id="dh_formkey"></div>`.

But I need it to output the HTML still, is there another step?

Thanks for the help.

**Comment by colinmollenhour** [comment]
DIEHARD_DYNAMIC_default doesn't exist by default so there is no "root" or "header" block to reference. Try putting all of your blocks directly in the handle as in the example in the README.
